#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          8
bspc config normal_border_color "#1e2d42"
bspc config active_border_color "#273b57"
bspc config focused_border_color "#264676"
bspc config presel_feedback_color "#e8ff71"

bspc config pointer_motion_interval 20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  1.0
bspc config bottom_monocle_padding  3.0
bspc config left_monocle_padding  3.0
bspc config right_monocle_padding  3.0

bspc rule -a Firefox::Places state=floating
bspc rule -a Gpicview state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
feh --bg-fill .config/bspwm/wallhaven-vgdgmm.jpg
